# Generated by Django 5.0.3 on 2024-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_member_address_member_city_member_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalbankdetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='personalbankdetail',
            name='passport_or_Id_no',
        ),
        migrations.RemoveField(
            model_name='personalbankdetail',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
